---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Don't build any extra formats, HTML and JSON will
# always be built by default.
formats: []

python:
  version: "3.11"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: "."
