---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Don't build any extra formats, HTML and JSON will
# always be built by default.
formats: []

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      # NOTE: ``pip install .`` also relies on ``BEZIER_NO_EXTENSION=true``
      #       being set in the Read the Docs configuration for the project
      path: "."
