---
version: 2
jobs:
  build:
    working_directory: /var/code/bezier/
    docker:
      - image: dhermes/bezier:latest
    environment:
      MATPLOTLIBRC: tests
      VIRTUALENV_NO_DOWNLOAD: "true"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check that all Cython generated files have been updated
          command: nox -s "update_generated(check=True)"
      - run:
          name: Unit tests in Python 3.7
          command: nox -s "unit-3.7"
      - run:
          name: Unit tests in Python 3.8
          command: nox -s "unit-3.8"
      - run:
          name: Unit tests in pypy3
          command: nox -s "unit-pypy3"
      - run:
          name: Unit tests AND line coverage in Python 3.9
          command: nox -s cover
      # # NOTE: Temporarily remove this; `lcov` is having phantom missing
      # #       lines in coverage (e.g. in a declaration).
      # - run:
      #     name: Fortran unit tests
      #     command: nox -s fortran_unit
      - run:
          name: Functional tests in Python 3.9
          command: nox -s "functional-3.9"
      - run:
          name: Run all doctests
          command: nox -s doctest
      - run:
          name: Build docs
          command: nox -s docs
      - run:
          name: Lint code for style issues
          command: nox -s lint
      - run:
          name: Check that test case examples are valid for JSON schema
          command: nox -s validate_functional_test_cases
      - deploy:
          name: Upload coverage to coveralls
          command: ./scripts/upload_coveralls.sh

workflows:
  version: 2
  push:
    jobs:
      - build
  monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
