---
version: 2
jobs:
  build:
    working_directory: /var/code/bezier/
    docker:
      - image: dhermes/bezier:latest
    environment:
      MATPLOTLIBRC: tests
    steps:
      - checkout
      - run:
          name: Check that all Cython generated files have been updated
          command: nox -s "update_generated(check=True)"
      - run:
          name: Unit tests in Python 2.7
          command: nox -s "unit-2.7"
      - run:
          name: Unit tests in Python 3.6
          command: nox -s "unit-3.6"
      - run:
          name: Unit tests in pypy
          command: nox -s "unit-pypy"
      - run:
          name: Unit tests AND line coverage in Python 3.7
          command: nox -s cover
      - run:
          name: Fortran unit tests
          command: nox -s fortran_unit
      - run:
          name: Functional tests in Python 3.7
          command: nox -s "functional-3.7"
      - run:
          name: Run all doctests
          command: nox -s doctest
      - run:
          name: Build docs
          command: nox -s docs
      - run:
          name: Lint code for style issues
          command: nox -s lint
      - run:
          name: Check the journaled `build_ext` commands
          command: nox -s "check_journal(machine='circleci')"
      - deploy:
          name: Upload coverage to coveralls
          command: |
            .nox/cover/bin/python -m pip install coveralls
            .nox/cover/bin/coveralls
